export { HeroSection, type HeroSectionProps } from './HeroSection';
export { WorkSection, type WorkSectionProps } from './WorkSection';
export { ExperienceSection, type ExperienceSectionProps } from './ExperienceSection';
export { CapabilitiesSection, type CapabilitiesSectionProps } from './CapabilitiesSection';
export { ActivitySection, type ActivitySectionProps } from './ActivitySection';
export { AboutSection, type AboutSectionProps } from './AboutSection';
export { ContactSection, type ContactSectionProps } from './ContactSection';
export { CaseStudyLayout, type CaseStudyLayoutProps } from './CaseStudyLayout';
export { NotFoundSection, type NotFoundSectionProps } from './NotFoundSection';
